// <auto-generated />
using System;
using IzmirGaz.Data.Concrete.EntityFremework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IzmirGaz.Data.Migrations
{
    [DbContext(typeof(IzmirGazContext))]
    [Migration("20201211075823_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("IzmirGaz.Entities.Concrete.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CompanyManagerFirstName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("CompanyManagerLastName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("CompanyManagerPhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<double>("CompanyPerformanceReport")
                        .HasColumnType("float");

                    b.Property<string>("CompanyPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("PercentageOfGasFired")
                        .HasColumnType("float");

                    b.Property<DateTime>("VisaDuration")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Anafartalar Mah. Cebeci sok No:11 Ödemiş/İzmir",
                            CompanyManagerFirstName = "Murat Evren",
                            CompanyManagerLastName = "DAMOĞLU",
                            CompanyManagerPhoneNumber = "232 384 11 29",
                            CompanyName = "Damoğlu Sıhhi Tesisat LTD ŞTI",
                            CompanyPerformanceReport = 0.0,
                            CompanyPhoneNumber = "506 384 11 29",
                            CreatedByName = "DefaultInsert",
                            CreatedDate = new DateTime(2020, 12, 11, 10, 58, 22, 979, DateTimeKind.Local).AddTicks(9829),
                            Email = "mevrend@gmail.com",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "DefaultInsert",
                            ModifiedDate = new DateTime(2020, 12, 11, 10, 58, 22, 980, DateTimeKind.Local).AddTicks(332),
                            Note = "DefaultValue",
                            PercentageOfGasFired = 0.0,
                            VisaDuration = new DateTime(2021, 12, 11, 10, 58, 22, 979, DateTimeKind.Local).AddTicks(7115)
                        },
                        new
                        {
                            Id = 2,
                            Address = "MuratBey Mah. Cebeci sok No:11 Ödemiş/İzmir",
                            CompanyManagerFirstName = "Hakan",
                            CompanyManagerLastName = "Ay",
                            CompanyManagerPhoneNumber = "232 384 55 99",
                            CompanyName = "Öz Sıhhi Tesisat LTD ŞTI",
                            CompanyPerformanceReport = 0.0,
                            CompanyPhoneNumber = "506 555 17 28",
                            CreatedByName = "DefaultInsert",
                            CreatedDate = new DateTime(2020, 12, 11, 10, 58, 22, 980, DateTimeKind.Local).AddTicks(932),
                            Email = "ozsihhi@gmail.com",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "DefaultInsert",
                            ModifiedDate = new DateTime(2020, 12, 11, 10, 58, 22, 980, DateTimeKind.Local).AddTicks(934),
                            Note = "DefaultValue",
                            PercentageOfGasFired = 0.0,
                            VisaDuration = new DateTime(2020, 12, 4, 10, 58, 22, 980, DateTimeKind.Local).AddTicks(839)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Nevzat Mah. Cebeci sok No:11 Ödemiş/İzmir",
                            CompanyManagerFirstName = "Hakan",
                            CompanyManagerLastName = "Ay",
                            CompanyManagerPhoneNumber = "232 384 77 77",
                            CompanyName = "Nevzat Sıhhi Tesisat LTD ŞTI",
                            CompanyPerformanceReport = 0.0,
                            CompanyPhoneNumber = "506 555 77 77",
                            CreatedByName = "DefaultInsert",
                            CreatedDate = new DateTime(2020, 12, 11, 10, 58, 22, 980, DateTimeKind.Local).AddTicks(945),
                            Email = "nevzat@gmail.com",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "DefaultInsert",
                            ModifiedDate = new DateTime(2020, 12, 11, 10, 58, 22, 980, DateTimeKind.Local).AddTicks(946),
                            Note = "DefaultValue",
                            PercentageOfGasFired = 0.0,
                            VisaDuration = new DateTime(2021, 12, 11, 10, 58, 22, 980, DateTimeKind.Local).AddTicks(938)
                        });
                });

            modelBuilder.Entity("IzmirGaz.Entities.Concrete.CompanyPersonnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PersonelImg")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PersonelType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyPersonnels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            CreatedByName = "DefaultInsert",
                            CreatedDate = new DateTime(2020, 12, 11, 10, 58, 22, 986, DateTimeKind.Local).AddTicks(1026),
                            FirstName = "Delal Abdullatif",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Abzak",
                            ModifiedByName = "DefaultInsert",
                            ModifiedDate = new DateTime(2020, 12, 11, 10, 58, 22, 986, DateTimeKind.Local).AddTicks(1041),
                            Note = "DefaultValue",
                            PersonelImg = "https://icons.iconarchive.com/icons/praveen/minimal-outline/128/profile-icon.png",
                            PersonelType = "Mühendis",
                            PhoneNumber = "555 000 00 00"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            CreatedByName = "DefaultInsert",
                            CreatedDate = new DateTime(2020, 12, 11, 10, 58, 22, 986, DateTimeKind.Local).AddTicks(1099),
                            FirstName = "Atahan",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Adanır",
                            ModifiedByName = "DefaultInsert",
                            ModifiedDate = new DateTime(2020, 12, 11, 10, 58, 22, 986, DateTimeKind.Local).AddTicks(1100),
                            Note = "DefaultValue",
                            PersonelImg = "https://icons.iconarchive.com/icons/praveen/minimal-outline/128/profile-icon.png",
                            PersonelType = "Tesisatcı",
                            PhoneNumber = "555 000 00 00"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 1,
                            CreatedByName = "DefaultInsert",
                            CreatedDate = new DateTime(2020, 12, 11, 10, 58, 22, 986, DateTimeKind.Local).AddTicks(1105),
                            FirstName = "Hacı Mehmet",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Adıgüzel",
                            ModifiedByName = "DefaultInsert",
                            ModifiedDate = new DateTime(2020, 12, 11, 10, 58, 22, 986, DateTimeKind.Local).AddTicks(1106),
                            Note = "DefaultValue",
                            PersonelImg = "https://icons.iconarchive.com/icons/praveen/minimal-outline/128/profile-icon.png",
                            PersonelType = "Tesisatcı",
                            PhoneNumber = "555 000 00 00"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 1,
                            CreatedByName = "DefaultInsert",
                            CreatedDate = new DateTime(2020, 12, 11, 10, 58, 22, 986, DateTimeKind.Local).AddTicks(1110),
                            FirstName = "Tutkum",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Ahmadı Asl",
                            ModifiedByName = "DefaultInsert",
                            ModifiedDate = new DateTime(2020, 12, 11, 10, 58, 22, 986, DateTimeKind.Local).AddTicks(1111),
                            Note = "DefaultValue",
                            PersonelImg = "https://icons.iconarchive.com/icons/praveen/minimal-outline/128/profile-icon.png",
                            PersonelType = "Tesisatcı",
                            PhoneNumber = "555 000 00 00"
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 2,
                            CreatedByName = "DefaultInsert",
                            CreatedDate = new DateTime(2020, 12, 11, 10, 58, 22, 986, DateTimeKind.Local).AddTicks(1116),
                            FirstName = "Recep Ali Samet",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Akdoğan",
                            ModifiedByName = "DefaultInsert",
                            ModifiedDate = new DateTime(2020, 12, 11, 10, 58, 22, 986, DateTimeKind.Local).AddTicks(1117),
                            Note = "DefaultValue",
                            PersonelImg = "https://icons.iconarchive.com/icons/praveen/minimal-outline/128/profile-icon.png",
                            PersonelType = "Mühendis",
                            PhoneNumber = "555 000 00 00"
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 2,
                            CreatedByName = "DefaultInsert",
                            CreatedDate = new DateTime(2020, 12, 11, 10, 58, 22, 986, DateTimeKind.Local).AddTicks(1121),
                            FirstName = "Ahmet Polat",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Aklar Çörekçi",
                            ModifiedByName = "DefaultInsert",
                            ModifiedDate = new DateTime(2020, 12, 11, 10, 58, 22, 986, DateTimeKind.Local).AddTicks(1122),
                            Note = "DefaultValue",
                            PersonelImg = "https://icons.iconarchive.com/icons/praveen/minimal-outline/128/profile-icon.png",
                            PersonelType = "Tesisatcı",
                            PhoneNumber = "555 000 00 00"
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = 2,
                            CreatedByName = "DefaultInsert",
                            CreatedDate = new DateTime(2020, 12, 11, 10, 58, 22, 986, DateTimeKind.Local).AddTicks(1126),
                            FirstName = "Ecem Hatice",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Akova",
                            ModifiedByName = "DefaultInsert",
                            ModifiedDate = new DateTime(2020, 12, 11, 10, 58, 22, 986, DateTimeKind.Local).AddTicks(1128),
                            Note = "DefaultValue",
                            PersonelImg = "https://icons.iconarchive.com/icons/praveen/minimal-outline/128/profile-icon.png",
                            PersonelType = "Tesisatcı",
                            PhoneNumber = "555 000 00 00"
                        },
                        new
                        {
                            Id = 8,
                            CompanyId = 2,
                            CreatedByName = "DefaultInsert",
                            CreatedDate = new DateTime(2020, 12, 11, 10, 58, 22, 986, DateTimeKind.Local).AddTicks(1132),
                            FirstName = "Selinti",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Al",
                            ModifiedByName = "DefaultInsert",
                            ModifiedDate = new DateTime(2020, 12, 11, 10, 58, 22, 986, DateTimeKind.Local).AddTicks(1133),
                            Note = "DefaultValue",
                            PersonelImg = "https://icons.iconarchive.com/icons/praveen/minimal-outline/128/profile-icon.png",
                            PersonelType = "Tesisatcı",
                            PhoneNumber = "555 000 00 00"
                        },
                        new
                        {
                            Id = 9,
                            CompanyId = 3,
                            CreatedByName = "DefaultInsert",
                            CreatedDate = new DateTime(2020, 12, 11, 10, 58, 22, 986, DateTimeKind.Local).AddTicks(1137),
                            FirstName = "Çisem",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Atok",
                            ModifiedByName = "DefaultInsert",
                            ModifiedDate = new DateTime(2020, 12, 11, 10, 58, 22, 986, DateTimeKind.Local).AddTicks(1138),
                            Note = "DefaultValue",
                            PersonelImg = "https://icons.iconarchive.com/icons/praveen/minimal-outline/128/profile-icon.png",
                            PersonelType = "Mühendis",
                            PhoneNumber = "555 000 00 00"
                        },
                        new
                        {
                            Id = 10,
                            CompanyId = 3,
                            CreatedByName = "DefaultInsert",
                            CreatedDate = new DateTime(2020, 12, 11, 10, 58, 22, 986, DateTimeKind.Local).AddTicks(1143),
                            FirstName = "Saime",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Avıandı",
                            ModifiedByName = "DefaultInsert",
                            ModifiedDate = new DateTime(2020, 12, 11, 10, 58, 22, 986, DateTimeKind.Local).AddTicks(1144),
                            Note = "DefaultValue",
                            PersonelImg = "https://icons.iconarchive.com/icons/praveen/minimal-outline/128/profile-icon.png",
                            PersonelType = "Tesisatcı",
                            PhoneNumber = "555 000 00 00"
                        },
                        new
                        {
                            Id = 11,
                            CompanyId = 3,
                            CreatedByName = "DefaultInsert",
                            CreatedDate = new DateTime(2020, 12, 11, 10, 58, 22, 986, DateTimeKind.Local).AddTicks(1148),
                            FirstName = "Alçiçek",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Bad",
                            ModifiedByName = "DefaultInsert",
                            ModifiedDate = new DateTime(2020, 12, 11, 10, 58, 22, 986, DateTimeKind.Local).AddTicks(1149),
                            Note = "DefaultValue",
                            PersonelImg = "https://icons.iconarchive.com/icons/praveen/minimal-outline/128/profile-icon.png",
                            PersonelType = "Tesisatcı",
                            PhoneNumber = "555 000 00 00"
                        },
                        new
                        {
                            Id = 12,
                            CompanyId = 3,
                            CreatedByName = "DefaultInsert",
                            CreatedDate = new DateTime(2020, 12, 11, 10, 58, 22, 986, DateTimeKind.Local).AddTicks(1153),
                            FirstName = "Mustafa Samed",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Beğenilmiş",
                            ModifiedByName = "DefaultInsert",
                            ModifiedDate = new DateTime(2020, 12, 11, 10, 58, 22, 986, DateTimeKind.Local).AddTicks(1155),
                            Note = "DefaultValue",
                            PersonelImg = "https://icons.iconarchive.com/icons/praveen/minimal-outline/128/profile-icon.png",
                            PersonelType = "Tesisatcı",
                            PhoneNumber = "555 000 00 00"
                        });
                });

            modelBuilder.Entity("IzmirGaz.Entities.Concrete.CompanyPersonnel", b =>
                {
                    b.HasOne("IzmirGaz.Entities.Concrete.Company", "Company")
                        .WithMany("CompanyPersonnels")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("IzmirGaz.Entities.Concrete.Company", b =>
                {
                    b.Navigation("CompanyPersonnels");
                });
#pragma warning restore 612, 618
        }
    }
}
