// <auto-generated />
using System;
using IzmirGaz.Data.Concrete.EntityFremework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IzmirGaz.Data.Migrations
{
    [DbContext(typeof(IzmirGazContext))]
    partial class IzmirGazContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("IzmirGaz.Entities.Concrete.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CompanyCertificateEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompanyCountry")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompanyManagerFirstName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("CompanyManagerLastName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("CompanyManagerPhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<double>("CompanyPerformanceReport")
                        .HasColumnType("float");

                    b.Property<string>("CompanyPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("PercentageOfGasFired")
                        .HasColumnType("float");

                    b.Property<DateTime>("VisaDuration")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyManagerPhoneNumber")
                        .IsUnique()
                        .HasFilter("[CompanyManagerPhoneNumber] IS NOT NULL");

                    b.HasIndex("CompanyPhoneNumber")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Anafartalar Mah. Cebeci sok No:11",
                            CompanyCertificateEndDate = new DateTime(2022, 12, 14, 14, 38, 47, 761, DateTimeKind.Local).AddTicks(9108),
                            CompanyCountry = "Ödemiş",
                            CompanyManagerFirstName = "Murat Evren",
                            CompanyManagerLastName = "DAMOĞLU",
                            CompanyManagerPhoneNumber = "232 384 11 29",
                            CompanyName = "Damoğlu Sıhhi Tesisat LTD ŞTI",
                            CompanyPerformanceReport = 0.0,
                            CompanyPhoneNumber = "506 384 11 29",
                            CreatedByName = "DefaultInsert",
                            CreatedDate = new DateTime(2020, 12, 14, 14, 38, 47, 762, DateTimeKind.Local).AddTicks(6149),
                            Email = "mevrend@gmail.com",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "DefaultInsert",
                            ModifiedDate = new DateTime(2020, 12, 14, 14, 38, 47, 762, DateTimeKind.Local).AddTicks(7345),
                            Note = "DefaultValue",
                            PercentageOfGasFired = 0.0,
                            VisaDuration = new DateTime(2021, 12, 14, 14, 38, 47, 761, DateTimeKind.Local).AddTicks(9880)
                        },
                        new
                        {
                            Id = 2,
                            Address = "MuratBey Mah. Cebeci sok No:11",
                            CompanyCertificateEndDate = new DateTime(2023, 12, 14, 14, 38, 47, 762, DateTimeKind.Local).AddTicks(8581),
                            CompanyCountry = "Tire",
                            CompanyManagerFirstName = "Hakan",
                            CompanyManagerLastName = "Ay",
                            CompanyManagerPhoneNumber = "232 384 55 99",
                            CompanyName = "Öz Sıhhi Tesisat LTD ŞTI",
                            CompanyPerformanceReport = 0.0,
                            CompanyPhoneNumber = "506 555 17 28",
                            CreatedByName = "DefaultInsert",
                            CreatedDate = new DateTime(2020, 12, 14, 14, 38, 47, 762, DateTimeKind.Local).AddTicks(8787),
                            Email = "ozsihhi@gmail.com",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "DefaultInsert",
                            ModifiedDate = new DateTime(2020, 12, 14, 14, 38, 47, 762, DateTimeKind.Local).AddTicks(8790),
                            Note = "DefaultValue",
                            PercentageOfGasFired = 0.0,
                            VisaDuration = new DateTime(2020, 12, 7, 14, 38, 47, 762, DateTimeKind.Local).AddTicks(8593)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Nevzat Mah. Cebeci sok No:11",
                            CompanyCertificateEndDate = new DateTime(2025, 12, 14, 14, 38, 47, 762, DateTimeKind.Local).AddTicks(8803),
                            CompanyCountry = "Bornova",
                            CompanyManagerFirstName = "Nevzat",
                            CompanyManagerLastName = "KadirAy",
                            CompanyManagerPhoneNumber = "232 384 77 77",
                            CompanyName = "Nevzat Sıhhi Tesisat LTD ŞTI",
                            CompanyPerformanceReport = 0.0,
                            CompanyPhoneNumber = "506 555 77 77",
                            CreatedByName = "DefaultInsert",
                            CreatedDate = new DateTime(2020, 12, 14, 14, 38, 47, 762, DateTimeKind.Local).AddTicks(8813),
                            Email = "nevzat@gmail.com",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "DefaultInsert",
                            ModifiedDate = new DateTime(2020, 12, 14, 14, 38, 47, 762, DateTimeKind.Local).AddTicks(8815),
                            Note = "DefaultValue",
                            PercentageOfGasFired = 0.0,
                            VisaDuration = new DateTime(2021, 12, 14, 14, 38, 47, 762, DateTimeKind.Local).AddTicks(8800)
                        });
                });

            modelBuilder.Entity("IzmirGaz.Entities.Concrete.CompanyPersonnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PersonelEmail")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PersonelImg")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<string>("PersonelType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PersonelEmail")
                        .IsUnique()
                        .HasFilter("[PersonelEmail] IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.ToTable("CompanyPersonnels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            CreatedByName = "DefaultInsert",
                            CreatedDate = new DateTime(2020, 12, 14, 14, 38, 47, 776, DateTimeKind.Local).AddTicks(1735),
                            FirstName = "Delal Abdullatif",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Abzak",
                            ModifiedByName = "DefaultInsert",
                            ModifiedDate = new DateTime(2020, 12, 14, 14, 38, 47, 776, DateTimeKind.Local).AddTicks(1768),
                            Note = "DefaultValue",
                            PersonelEmail = "default@gmail.com",
                            PersonelImg = "https://icons.iconarchive.com/icons/praveen/minimal-outline/128/profile-icon.png",
                            PersonelType = "Mühendis",
                            PhoneNumber = "555 000 00 00"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            CreatedByName = "DefaultInsert",
                            CreatedDate = new DateTime(2020, 12, 14, 14, 38, 47, 776, DateTimeKind.Local).AddTicks(1905),
                            FirstName = "Atahan",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Adanır",
                            ModifiedByName = "DefaultInsert",
                            ModifiedDate = new DateTime(2020, 12, 14, 14, 38, 47, 776, DateTimeKind.Local).AddTicks(1908),
                            Note = "DefaultValue",
                            PersonelEmail = "default1@gmail.com",
                            PersonelImg = "https://icons.iconarchive.com/icons/praveen/minimal-outline/128/profile-icon.png",
                            PersonelType = "Tesisatcı",
                            PhoneNumber = "555 000 00 01"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 1,
                            CreatedByName = "DefaultInsert",
                            CreatedDate = new DateTime(2020, 12, 14, 14, 38, 47, 776, DateTimeKind.Local).AddTicks(1918),
                            FirstName = "Hacı Mehmet",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Adıgüzel",
                            ModifiedByName = "DefaultInsert",
                            ModifiedDate = new DateTime(2020, 12, 14, 14, 38, 47, 776, DateTimeKind.Local).AddTicks(1921),
                            Note = "DefaultValue",
                            PersonelEmail = "default2@gmail.com",
                            PersonelImg = "https://icons.iconarchive.com/icons/praveen/minimal-outline/128/profile-icon.png",
                            PersonelType = "Tesisatcı",
                            PhoneNumber = "555 000 00 02"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 1,
                            CreatedByName = "DefaultInsert",
                            CreatedDate = new DateTime(2020, 12, 14, 14, 38, 47, 776, DateTimeKind.Local).AddTicks(1929),
                            FirstName = "Tutkum",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Ahmadı Asl",
                            ModifiedByName = "DefaultInsert",
                            ModifiedDate = new DateTime(2020, 12, 14, 14, 38, 47, 776, DateTimeKind.Local).AddTicks(1931),
                            Note = "DefaultValue",
                            PersonelEmail = "default3@gmail.com",
                            PersonelImg = "https://icons.iconarchive.com/icons/praveen/minimal-outline/128/profile-icon.png",
                            PersonelType = "Tesisatcı",
                            PhoneNumber = "555 000 00 03"
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 2,
                            CreatedByName = "DefaultInsert",
                            CreatedDate = new DateTime(2020, 12, 14, 14, 38, 47, 776, DateTimeKind.Local).AddTicks(1939),
                            FirstName = "Recep Ali Samet",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Akdoğan",
                            ModifiedByName = "DefaultInsert",
                            ModifiedDate = new DateTime(2020, 12, 14, 14, 38, 47, 776, DateTimeKind.Local).AddTicks(1941),
                            Note = "DefaultValue",
                            PersonelEmail = "default4@gmail.com",
                            PersonelImg = "https://icons.iconarchive.com/icons/praveen/minimal-outline/128/profile-icon.png",
                            PersonelType = "Mühendis",
                            PhoneNumber = "555 000 00 04"
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 2,
                            CreatedByName = "DefaultInsert",
                            CreatedDate = new DateTime(2020, 12, 14, 14, 38, 47, 776, DateTimeKind.Local).AddTicks(1950),
                            FirstName = "Ahmet Polat",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Aklar Çörekçi",
                            ModifiedByName = "DefaultInsert",
                            ModifiedDate = new DateTime(2020, 12, 14, 14, 38, 47, 776, DateTimeKind.Local).AddTicks(1952),
                            Note = "DefaultValue",
                            PersonelEmail = "default5@gmail.com",
                            PersonelImg = "https://icons.iconarchive.com/icons/praveen/minimal-outline/128/profile-icon.png",
                            PersonelType = "Tesisatcı",
                            PhoneNumber = "555 000 00 05"
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = 2,
                            CreatedByName = "DefaultInsert",
                            CreatedDate = new DateTime(2020, 12, 14, 14, 38, 47, 776, DateTimeKind.Local).AddTicks(1960),
                            FirstName = "Ecem Hatice",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Akova",
                            ModifiedByName = "DefaultInsert",
                            ModifiedDate = new DateTime(2020, 12, 14, 14, 38, 47, 776, DateTimeKind.Local).AddTicks(1962),
                            Note = "DefaultValue",
                            PersonelEmail = "default6@gmail.com",
                            PersonelImg = "https://icons.iconarchive.com/icons/praveen/minimal-outline/128/profile-icon.png",
                            PersonelType = "Tesisatcı",
                            PhoneNumber = "555 000 00 06"
                        },
                        new
                        {
                            Id = 8,
                            CompanyId = 2,
                            CreatedByName = "DefaultInsert",
                            CreatedDate = new DateTime(2020, 12, 14, 14, 38, 47, 776, DateTimeKind.Local).AddTicks(1970),
                            FirstName = "Selinti",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Al",
                            ModifiedByName = "DefaultInsert",
                            ModifiedDate = new DateTime(2020, 12, 14, 14, 38, 47, 776, DateTimeKind.Local).AddTicks(1973),
                            Note = "DefaultValue",
                            PersonelEmail = "default7@gmail.com",
                            PersonelImg = "https://icons.iconarchive.com/icons/praveen/minimal-outline/128/profile-icon.png",
                            PersonelType = "Tesisatcı",
                            PhoneNumber = "555 000 00 07"
                        },
                        new
                        {
                            Id = 9,
                            CompanyId = 3,
                            CreatedByName = "DefaultInsert",
                            CreatedDate = new DateTime(2020, 12, 14, 14, 38, 47, 776, DateTimeKind.Local).AddTicks(1980),
                            FirstName = "Çisem",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Atok",
                            ModifiedByName = "DefaultInsert",
                            ModifiedDate = new DateTime(2020, 12, 14, 14, 38, 47, 776, DateTimeKind.Local).AddTicks(1983),
                            Note = "DefaultValue",
                            PersonelEmail = "default8@gmail.com",
                            PersonelImg = "https://icons.iconarchive.com/icons/praveen/minimal-outline/128/profile-icon.png",
                            PersonelType = "Mühendis",
                            PhoneNumber = "555 000 00 08"
                        },
                        new
                        {
                            Id = 10,
                            CompanyId = 3,
                            CreatedByName = "DefaultInsert",
                            CreatedDate = new DateTime(2020, 12, 14, 14, 38, 47, 776, DateTimeKind.Local).AddTicks(1992),
                            FirstName = "Saime",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Avıandı",
                            ModifiedByName = "DefaultInsert",
                            ModifiedDate = new DateTime(2020, 12, 14, 14, 38, 47, 776, DateTimeKind.Local).AddTicks(1994),
                            Note = "DefaultValue",
                            PersonelEmail = "default9@gmail.com",
                            PersonelImg = "https://icons.iconarchive.com/icons/praveen/minimal-outline/128/profile-icon.png",
                            PersonelType = "Tesisatcı",
                            PhoneNumber = "555 000 00 09"
                        },
                        new
                        {
                            Id = 11,
                            CompanyId = 3,
                            CreatedByName = "DefaultInsert",
                            CreatedDate = new DateTime(2020, 12, 14, 14, 38, 47, 776, DateTimeKind.Local).AddTicks(2001),
                            FirstName = "Alçiçek",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Bad",
                            ModifiedByName = "DefaultInsert",
                            ModifiedDate = new DateTime(2020, 12, 14, 14, 38, 47, 776, DateTimeKind.Local).AddTicks(2004),
                            Note = "DefaultValue",
                            PersonelEmail = "default10@gmail.com",
                            PersonelImg = "https://icons.iconarchive.com/icons/praveen/minimal-outline/128/profile-icon.png",
                            PersonelType = "Tesisatcı",
                            PhoneNumber = "555 000 00 10"
                        },
                        new
                        {
                            Id = 12,
                            CompanyId = 3,
                            CreatedByName = "DefaultInsert",
                            CreatedDate = new DateTime(2020, 12, 14, 14, 38, 47, 776, DateTimeKind.Local).AddTicks(2011),
                            FirstName = "Mustafa Samed",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Beğenilmiş",
                            ModifiedByName = "DefaultInsert",
                            ModifiedDate = new DateTime(2020, 12, 14, 14, 38, 47, 776, DateTimeKind.Local).AddTicks(2014),
                            Note = "DefaultValue",
                            PersonelEmail = "default11@gmail.com",
                            PersonelImg = "https://icons.iconarchive.com/icons/praveen/minimal-outline/128/profile-icon.png",
                            PersonelType = "Tesisatcı",
                            PhoneNumber = "555 000 00 11"
                        });
                });

            modelBuilder.Entity("IzmirGaz.Entities.Concrete.CompanyPersonnel", b =>
                {
                    b.HasOne("IzmirGaz.Entities.Concrete.Company", "Company")
                        .WithMany("CompanyPersonnels")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("IzmirGaz.Entities.Concrete.Company", b =>
                {
                    b.Navigation("CompanyPersonnels");
                });
#pragma warning restore 612, 618
        }
    }
}
